// <auto-generated />
namespace ASP.NET_PersonControl.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class PriceTotal : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(PriceTotal));
        
        string IMigrationMetadata.Id
        {
            get { return "201809242331582_PriceTotal"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
